# Generated by Django 3.0.7 on 2024-03-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=15)),
                ('slogan', models.CharField(max_length=15)),
                ('tipo', models.CharField(choices=[('A', 'Maior Qualidade'), ('B', 'Boa Media'), ('C', 'Media Qualidade'), ('D', 'Pior Qualidade')], default='C', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('codigo', models.CharField(max_length=9)),
                ('valor', models.CharField(max_length=5)),
                ('validade', models.DateField()),
            ],
        ),
    ]
